data_root_dir: "./data/"
results_root_dir: "./results/"
dataset:
  2700642-training-no-defect:
    category: "training"
    product_name: "2700642"
    name: "2700642-training/no-defect"
    type: "no-defect"
    subtype: "missing"
    loc: ""
  2700642-testing-defect-bottom-right:
    category: "testing"
    product_name: "2700642"
    name: "2700642-testing/defect-bottom-right"
    type: "defect"
    subtype: "missing"
    loc: "connector_bottom_right"
  2700642-testing-defect-bottom-left:
    category: "testing"
    product_name: "2700642"
    name: "2700642-testing/defect-bottom-left"
    type: "defect"
    subtype: "missing"
    loc: "connector_bottom_left"
  2700642-testing-defect-top-right:
    category: "testing"
    product_name: "2700642"
    name: "2700642-testing/defect-top-right"
    type: "defect"
    subtype: "missing"
    loc: "connector_top_right"
  2700642-testing-defect-top-left:
    category: "testing"
    product_name: "2700642"
    name: "2700642-testing/defect-top-left"
    type: "defect"
    subtype: "missing"
    loc: "connector_top_left"
  bus_coppler_gray-training-no-defect:
    category: "training"
    product_name: "bus_coppler_gray"
    name: "bus_coppler_gray-training/no-defect"
    type: "no-defect"
    subtype: "no-defect"
    loc: ""
  bus_coppler_gray-testing-defect-rail-cr:
    category: "testing"
    product_name: "bus_coppler_gray"
    name: "bus_coppler_gray-testing/defect-rail-cr"
    type: "defect"
    subtype: "missing"
    loc: "rail-cr"
  bus_coppler_gray-testing-defect-rail-l:
    category: "testing"
    product_name: "bus_coppler_gray"
    name: "bus_coppler_gray-testing/defect-rail-l"
    type: "defect"
    subtype: "missing"
    loc: "rail-l"
  bus_coppler_gray-testing-defect-mount-clipper:
    category: "testing"
    product_name: "bus_coppler_gray"
    name: "bus_coppler_gray-testing/defect-mount-clipper"
    type: "defect"
    subtype: "missing"
    loc: "mount-clipper"
  bus_coppler_gray-testing-defect-exchange-rails-cl-cr:
    category: "testing"
    product_name: "bus_coppler_gray"
    name: "bus_coppler_gray-testing/defect-exchange-rails-cl-cr"
    type: "defect"
    subtype: "texture"
    loc: "exchange-rails-cl-cr"
  bus_coppler_gray-testing-defect-exchange-rails-l-cr:
    category: "testing"
    product_name: "bus_coppler_gray"
    name: "bus_coppler_gray-testing/defect-exchange-rails-l-cr"
    type: "defect"
    subtype: "missing_exchange"
    loc: "exchange-rails-l-cr"
  bus_coppler_green-training-no-defect:
    category: "training"
    product_name: "bus_coppler_green"
    name: "bus_coppler_green-training/no-defect"
    type: "no-defect"
    subtype: "no-defect"
    loc: ""
  bus_coppler_green-testing-defect-rail-cr:
    category: "testing"
    product_name: "bus_coppler_green"
    name: "bus_coppler_green-testing/defect-rail-cr"
    type: "defect"
    subtype: "missing"
    loc: "rail-cr"
  bus_coppler_green-testing-defect-rail-l:
    category: "testing"
    product_name: "bus_coppler_green"
    name: "bus_coppler_green-testing/defect-rail-l"
    type: "defect"
    subtype: "missing"
    loc: "rail-l"
  bus_coppler_green-testing-defect-mount-clipper:
    category: "testing"
    product_name: "bus_coppler_green"
    name: "bus_coppler_green-testing/defect-mount-clipper"
    type: "defect"
    subtype: "missing"
    loc: "mount-clipper"
  bus_coppler_green-testing-defect-exchange-rails-cl-cr:
    category: "testing"
    product_name: "bus_coppler_green"
    name: "bus_coppler_green-testing/defect-exchange-rails-cl-cr"
    type: "defect"
    subtype: "texture"
    loc: "exchange-rails-cl-cr"
  bus_coppler_green-testing-defect-exchange-rails-l-cr:
    category: "testing"
    product_name: "bus_coppler_green"
    name: "bus_coppler_green-testing/defect-exchange-rails-l-cr"
    type: "defect"
    subtype: "missing_exchange"
    loc: "exchange-rails-l-cr"
  switch_8_port-training-no-defect:
    category: "training"
    product_name: "switch_8_port"
    name: "switch_8_port-training/no-defect"
    type: "no-defect"
    subtype: "no-defect"
    loc: ""
  switch_8_port-testing-defect-connector-side:
    category: "testing"
    product_name: "switch_8_port"
    name: "switch_8_port-testing/defect-connector-side"
    type: "defect"
    subtype: "missing"
    loc: "connector_side"
  switch_8_port-testing-defect-mount-clipper:
    category: "testing"
    product_name: "switch_8_port"
    name: "switch_8_port-testing/defect-mount-clipper"
    type: "defect"
    subtype: "missing"
    loc: "mount_clipper"
  switch_8_port-testing-defect-exchange-rj-45:
    category: "testing"
    product_name: "switch_8_port"
    name: "switch_8_port-testing/defect-exchange-rj-45"
    type: "defect"
    subtype: "texture"
    loc: "exchange-rj-45"
  switch_16_port-training-no-defect:
    category: "training"
    product_name: "switch_16_port"
    name: "switch_16_port-training/no-defect"
    type: "no-defect"
    subtype: "no-defect"
    loc: ""
  switch_16_port-testing-defect-connector-side:
    category: "testing"
    product_name: "switch_16_port"
    name: "switch_16_port-testing/defect-connector-side"
    type: "defect"
    subtype: "missing"
    loc: "connector_side"
  switch_16_port-testing-defect-mount-clipper:
    category: "testing"
    product_name: "switch_16_port"
    name: "switch_16_port-testing/defect-mount-clipper"
    type: "defect"
    subtype: "missing"
    loc: "mount_clipper"
  switch_16_port-testing-defect-exchange-rj-45:
    category: "testing"
    product_name: "switch_16_port"
    name: "switch_16_port-testing/defect-exchange-rj-45"
    type: "defect"
    subtype: "texture"
    loc: "exchange-rj-45"
